### ISSUE TITLE
new NR bands in user interface

### ISSUE THREAD

**Issue by lightful** [mroczis/netmonster-core#60]
For a long time I think that my phone didn't receive the N78 band, and that was a compeling reason to upgrade to Android 13 (which I don't like a lot). But I finally have just seen it "hidden" in the bands detailed listing. Netmonster (beta) does not reports its name (e.g. as "3500") but can be infered by the ARFCN by... [power users on telephony](https://www.cellmapper.net/arfcn?net=NR&ARFCN=640704&MCC=0).

These bands appear usually during data transfers, so it would be helpful not only to associate the name, but likely also to report them besides the "5G · NSA" legend and maybe in the notification (since the bands listing is continuously changing and scrolling up & down).

The fact that EARFCN and ARFCN are located at "different places" in the listing, makes it also more difficult to revise the listing before it refreshs. The lack of name and address "below" the N78 band also don't helps (I tend to associate these fields from the previous band):

![cband](https://user-images.githubusercontent.com/10393152/209004742-65d68311-9e14-4884-820f-0332485b1481.jpg)

In Spain N78 it is very popular; in the last day I recall having seen at my home 648384, 636576 and 640704 (from Vodafone, Telefonica, Orange: the related frequencies match the new ranges reassigned this very same year).

The N28 band also appears occasionally.

As an aside note, after upgrading to Android 13, my phone now only shows a single notification icon (instead of one for "each SIM") and not necessarily the one you'd like to see (in Android 11 it there were two icons, although the order was somewhat random).

All in all, Netmonster (I'm a betatester) is a great tool for everyone (e.g. it reveals the actual underlaying carrier in use, when a single SIM uses several networks, as in Spain with operator Yoigo, which may be using Yoigo/Orange/Movistar networks). In fact, an option to show the actual carrier name from the active SIM in the notification area would be a great feature (I currently don't use Yoigo, but at the time I would have loved the feature).

**Comment by mroczis** [comment]
Your bug report contains multiple questions, each targeting different codebase. Let's break them down.

**ARFCN to band number (NetMonster Core)**
ARFCNs you are mentioning fit multiple bands. If you device reports only ARFCN then band (+ band name) need to be deduced from that number. For example ARFCN 640704 can be n48 (3500), n77 (3500) and n78 (3700). In this case NetMonster Core cannot deduce band number and even band name since there are multiple conflicting candidates.

**Notification (NetMonster app)**
There's no behaviour change in NetMonster's source code and it processes data the same way whilst on Android 11 or 13. If notification design (and content) changed after you have updated the system, the blame should be on your manufacturer. Especially if SIM 1 and 2 in notification are switching I'd assume that your device manufacturer "optimised" something.

**Carrier name (NetMonster app)**
Thanks for suggesting this feature. Will have a look what can be done.

**Comment by eladts** [comment]
I have a similar issue where NetMonster misidentifies NR SA n41 that T-Mobile US uses as 2600. It does correctly identify NR NSA n41 as 2500. A possible solution of this band ambiguity is to have in the database rules for each carrier. T-Mobile US uses n41 and never uses n38, so any ambiguous ARFCN on their network should resolve to n41. These rules can be even automatically built from the NR NSA data, as it is highly unlikely for a carrier to use any band for SA but not for NSA.

**Comment by eladts** [comment]
Here is a report for NR SA n41 (2500) misidentified as n38 (2600). When present in NR NSA, n41 is not identified at all.

[report.txt](https://github.com/mroczis/netmonster-core/files/10531260/report.txt)

**Comment by eladts** [comment]
@mroczis Thanks for the fix for n41. Looking at the code, I found several other inconsistencies between LTE and NR band names:

- B66 AWS vs n66 2100
- B70 AWS vs n70 2000

Please fix those as well.

**Comment by mroczis** [comment]
Should be resolved now

**Comment by eladts** [comment]
@mroczis You added the NR bands n46 and n47, but the LTE bands B46 and B47 are still missing in [BandTableLte.kt](https://github.com/mroczis/netmonster-core/blob/master/library/src/main/java/cz/mroczis/netmonster/core/db/BandTableLte.kt). B46 is actually supported by phones and deployed by carriers in the US.
